version: '3.8'

services:
  # CCDI Federation Service
  ccdi-federation-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      # App settings
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=true
      - APP_LOG_LEVEL=INFO
      
      # Database settings
      - DB_URI=bolt://memgraph:7687
      - DB_USER=
      - DB_PASSWORD=
      - DB_DATABASE=memgraph
      - DB_MAX_CONNECTIONS=10
      - DB_CONNECTION_TIMEOUT=30
      - DB_MAX_TRANSACTION_RETRY_TIME=15
      
      # Cache settings
      - CACHE_ENABLED=true
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
      - CACHE_REDIS_PASSWORD=
      - CACHE_COUNT_TTL=300
      - CACHE_SUMMARY_TTL=600
      
      # CORS settings
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
      
      # Pagination settings
      - PAGINATION_DEFAULT_PER_PAGE=20
      - PAGINATION_MAX_PER_PAGE=100
    depends_on:
      - memgraph
      - redis
    networks:
      - ccdi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Memgraph Database
  memgraph:
    image: memgraph/memgraph:2.11.1
    ports:
      - "7687:7687"
      - "7444:7444"  # Memgraph Lab
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - memgraph-data:/var/lib/memgraph
    networks:
      - ccdi-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 1;' | mgconsole --host localhost --port 7687 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ccdi-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: redis-server --appendonly yes

  # Memgraph Lab (Web UI for database)
  memgraph-lab:
    image: memgraph/lab:2.11.1
    ports:
      - "3000:3000"
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - memgraph
    networks:
      - ccdi-network

volumes:
  memgraph-data:
  redis-data:

networks:
  ccdi-network:
    driver: bridge
